# Regenerates the README marketing screenshots.
#
# Two pipelines (docs/testing.md "README screenshots"):
#
# 1. Script-driven scenes ($jsScenes below): a fresh unattended patchy.exe runs a
#    scripts\dev\readme-shots\*.js scene through --run-script on the REAL windows
#    platform, so every installed font renders (the offscreen platform enumerates
#    none). The app window appears on screen for a few seconds per scene; the
#    capture itself never raises or focuses it. PATCHY_SETTINGS_DIR isolates the
#    run from the user's real Patchy settings (recent files, window geometry),
#    PATCHY_NO_SINGLE_INSTANCE=1 keeps it out of any running instance, and the
#    DPI pins keep shots at their logical size on scaled monitors.
#
# 2. Offscreen test scenes (everything else): the shot_readme_* scenes in
#    patchy_ui_visual_tests run offscreen and their PNGs are copied out of
#    test-artifacts/. These migrate to pipeline 1 over time; the test scenes
#    stay in the suite as regression smoke tests either way.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\make-readme-screenshots.ps1 [-SkipBuild] [-Scene camera_raw]
#
# Some scenes need local fixtures (not committed): akiko_cycling_okinawa.jpg,
# ipad_main_v04.psd, mow_master.psd in local-test-fixtures/psd/, the Camera Raw
# scene's local-test-fixtures/raw/fujifilm_xt1.raf (CC0, raw.pixls.us), and the
# Affinity scene's local-test-fixtures/af-spike/corpus/tips.af. Scenes whose
# fixture is missing are skipped with a [SKIP] line.
param(
    [switch]$SkipBuild,
    [string]$Scene = 'shot_readme'
)

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$outDir = Join-Path $repo 'docs\images\screenshots'
$buildDir = Join-Path $repo 'build\release'

# DWM rounds every window Patchy frames itself, but it clips in the compositor
# (src/ui/window_effects.cpp, DWMWCP_ROUND), so a grabbed window is square. The
# offscreen scenes get their corners in save_readme_shot; script-driven scenes capture
# through the app's own patchy.ui.captureWindow, so they get them here. Keep the radius
# in step with kReadmeWindowCornerRadius in tests/ui/readme_screenshot_test_support.hpp.
function Set-RoundedWindowCorners {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [int]$Radius = 8
    )
    Add-Type -AssemblyName System.Drawing
    # Read through a MemoryStream: Bitmap::FromFile would hold the file open and the
    # rounded copy has to be written back over it.
    $stream = New-Object System.IO.MemoryStream(, [System.IO.File]::ReadAllBytes($Path))
    try {
        $source = [System.Drawing.Bitmap]::FromStream($stream)
        try {
            $rounded = New-Object System.Drawing.Bitmap(
                $source.Width, $source.Height, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
            try {
                $graphics = [System.Drawing.Graphics]::FromImage($rounded)
                $shape = New-Object System.Drawing.Drawing2D.GraphicsPath
                $brush = New-Object System.Drawing.TextureBrush($source)
                try {
                    $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
                    $graphics.Clear([System.Drawing.Color]::Transparent)
                    $diameter = $Radius * 2
                    $shape.AddArc(0, 0, $diameter, $diameter, 180, 90)
                    $shape.AddArc($source.Width - $diameter, 0, $diameter, $diameter, 270, 90)
                    $shape.AddArc($source.Width - $diameter, $source.Height - $diameter, $diameter, $diameter, 0, 90)
                    $shape.AddArc(0, $source.Height - $diameter, $diameter, $diameter, 90, 90)
                    $shape.CloseFigure()
                    # FillPath honors SmoothingMode; SetClip would give hard-edged
                    # aliased corners instead, because GDI+ regions are not antialiased.
                    $graphics.FillPath($brush, $shape)
                } finally {
                    $brush.Dispose()
                    $shape.Dispose()
                    $graphics.Dispose()
                }
                $rounded.Save($Path, [System.Drawing.Imaging.ImageFormat]::Png)
            } finally {
                $rounded.Dispose()
            }
        } finally {
            $source.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

# Scenes generated by driving the real app through the scripting CLI.
# Key = the README image base name; Script = the scene; Args = extra
# --script-arg tokens; Fixture = skip the scene when this file is missing.
$jsScenes = [ordered]@{
    'affinity_import' = @{
        Script  = Join-Path $repo 'scripts\dev\readme-shots\affinity_import.js'
        Args    = @("af=$(Join-Path $repo 'local-test-fixtures\af-spike\corpus\tips.af')")
        Fixture = Join-Path $repo 'local-test-fixtures\af-spike\corpus\tips.af'
    }
}

$sceneName = $Scene -replace '^shot_readme_?', ''
$runAll = [string]::IsNullOrEmpty($sceneName)
$jsToRun = @()
if ($runAll) {
    $jsToRun = @($jsScenes.Keys)
} elseif ($jsScenes.Contains($sceneName)) {
    $jsToRun = @($sceneName)
}
$runOffscreen = $runAll -or -not $jsScenes.Contains($sceneName)

if (-not $SkipBuild) {
    Push-Location $repo
    try {
        cmd /s /c 'scripts\vs-env.bat -arch=x64 -host_arch=x64 >nul && "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build --preset release --target patchy patchy_ui_visual_tests'
        if ($LASTEXITCODE -ne 0) { throw "build failed (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
}
New-Item -ItemType Directory -Force $outDir | Out-Null

# --- Pipeline 2: offscreen test scenes -------------------------------------
if ($runOffscreen) {
    $exe = Join-Path $buildDir 'patchy_ui_visual_tests.exe'
    if (-not (Test-Path $exe)) { throw "missing $exe (run without -SkipBuild)" }
    $filter = if ($Scene.StartsWith('shot_readme')) { $Scene } else { "shot_readme_$Scene" }
    $artifactPattern = "$filter*.png"
    $artifactDir = Join-Path $buildDir 'test-artifacts'
    if (Test-Path $artifactDir) {
        Get-ChildItem (Join-Path $artifactDir $artifactPattern) -ErrorAction SilentlyContinue |
            Remove-Item -Force
    }

    Push-Location $buildDir
    try {
        $env:QT_QPA_PLATFORM = 'offscreen'
        $env:PATCHY_NO_SOUND = '1'
        & $exe $filter
        if ($LASTEXITCODE -ne 0) { throw "screenshot scenes failed (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
        Remove-Item Env:QT_QPA_PLATFORM -ErrorAction SilentlyContinue
    }

    $shots = @(Get-ChildItem (Join-Path $artifactDir $artifactPattern) -ErrorAction SilentlyContinue)
    if ($shots.Count -eq 0 -and $jsToRun.Count -eq 0) { throw "no $artifactPattern artifacts were produced" }
    foreach ($shot in $shots) {
        $name = $shot.Name -replace '^shot_readme_', ''
        if ($jsScenes.Contains([System.IO.Path]::GetFileNameWithoutExtension($name))) {
            continue  # migrated scene: the script-driven pipeline owns this image
        }
        $dest = Join-Path $outDir $name
        Copy-Item $shot.FullName $dest -Force
        Write-Host "updated $dest"
    }
}

# --- Pipeline 1: script-driven scenes (real app, real fonts) ----------------
foreach ($name in $jsToRun) {
    # NOT $scene: PowerShell variables are case-insensitive, and assigning to
    # $scene would cast the hashtable into the typed [string]$Scene parameter.
    $spec = $jsScenes[$name]
    if ($spec.Fixture -and -not (Test-Path $spec.Fixture)) {
        Write-Host "[SKIP] $name (missing $($spec.Fixture))"
        continue
    }
    $patchyExe = Join-Path $buildDir 'patchy.exe'
    if (-not (Test-Path $patchyExe)) { throw "missing $patchyExe (run without -SkipBuild)" }

    $png = Join-Path $outDir "$name.png"
    $scriptOut = Join-Path $buildDir "readme-shot-$name.txt"
    Remove-Item $scriptOut -ErrorAction SilentlyContinue

    $env:PATCHY_NO_SINGLE_INSTANCE = '1'
    $env:PATCHY_NO_SOUND = '1'
    $env:PATCHY_SETTINGS_DIR = Join-Path $buildDir 'readme-shot-settings'
    $env:QT_ENABLE_HIGHDPI_SCALING = '0'
    $env:QT_FONT_DPI = '96'
    Remove-Item Env:QT_QPA_PLATFORM -ErrorAction SilentlyContinue
    try {
        $argList = @('--run-script', $spec.Script, '--script-output', $scriptOut, '--script-arg', "out=$png")
        foreach ($extra in $spec.Args) { $argList += @('--script-arg', $extra) }
        $proc = Start-Process -FilePath $patchyExe -ArgumentList $argList -PassThru
        if (-not $proc.WaitForExit(180000)) {
            $proc.Kill()
            throw "$name scene timed out"
        }
    } finally {
        Remove-Item Env:PATCHY_NO_SINGLE_INSTANCE, Env:PATCHY_SETTINGS_DIR, Env:QT_ENABLE_HIGHDPI_SCALING, Env:QT_FONT_DPI -ErrorAction SilentlyContinue
    }

    $log = if (Test-Path $scriptOut) { Get-Content $scriptOut -Raw } else { '' }
    if ($proc.ExitCode -ne 0 -or $log -notmatch '\[done\]') {
        throw "$name scene failed (exit $($proc.ExitCode)): $log"
    }
    if (-not (Test-Path $png)) { throw "$name scene reported done but wrote no $png" }
    Set-RoundedWindowCorners -Path $png
    Write-Host "updated $png"
}
